### ISSUE TITLE
[Crash Report] Using Adventurer's Pickaxe crashes the game (invalid tool check)

### ISSUE THREAD

**Issue by Desempregago** [Necr0/ConvenientAdditions#25]
The title explains itself.

java.lang.NullPointerException: Unexpected error
	at convenientadditions.item.tools.adventurersPickaxe.ItemAdventurersPickaxe.isEffective(ItemAdventurersPickaxe.java:60)
	at convenientadditions.item.tools.adventurersPickaxe.ItemAdventurersPickaxe.func_150893_a(ItemAdventurersPickaxe.java:46)
	at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:191)
	at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:523)
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:820)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:210)
	at net.minecraft.block.Block.func_180647_a(Block.java:545)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:412)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by Desempregago** [comment]
Latest 1.11.2, btw

**Comment by QbDesu** [comment]
Should be fixed in the next version. It should be available [here](https://minecraft.curseforge.com/projects/convenient-additions/files/2422733) as soon as it is approved.
